### ISSUE TITLE
Recording pre release issue tracker

### ISSUE THREAD

**Issue by ArsenArsen** [ArsenArsen/KShare#6]
[Blog post](https://blog.arsenarsen.com/posts/kshare-recording-branch-finish-up)

Recording is pretty much complete, but this time I don't want to go wrong and push out a broken feature.

Dear users, I am asking for your help. Use this branch. Find bugs in it. Comment on this PR, so I can keep track.

**Known bugs:** `[is fixed] <fix branch (if applicable)> <short summary>`
* [x] [master] Custom uploader JSON modifier error 
* [x] [feature/recording] Improper error handling
* [x] [feature/recording] Uploader limit lacking
* [x] [actually never was an issue] [1] Clipboard not working with recorded content

[1] There was actually no issue, according to my tests.
Test code:
```cpp
#include <iostream>
#include <QApplication>
#include <QDebug>
#include <QClipboard>
#include <QMimeData>
#include <QFile>

int main(int argc, char** argv) {
	QApplication a(argc, argv);
	auto data = QApplication::clipboard()->mimeData();
	qDebug() << data->formats() << data->data(data->formats()[0]);
	QFile f("video1.mp4");
	f.open(QIODevice::WriteOnly);
	f.write(data->data(data->formats()[0]));
	f.close();
}
```
Compile with: `g++ -fPIC -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ <file> -lQt5Gui -lQt5Core -lQt5Widgets`

**Comment by ArsenArsen** [comment]
As no one reported anything broken in these two weeks, I am closing the issue.
